language: cpp

compiler: 
 - gcc

notifications:
  on_success: change
  on_failure: always
  template:
   - "it's %{author}'s turn to pay the next round of drinks for the massacre he caused in %{repository}: %{build_url}"

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq cdbs cmake libboost-dev libboost-thread-dev libboost-filesystem-dev libmsgpack-dev

before_script:
 - mkdir build && cd build

script:
 - cmake -DENABLE_TESTING=ON .. && make 
 - src/tests/blackhole-tests
