sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev libboost-thread-dev libboost-system-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DENABLE_TESTING=ON .. && make
  - ./blackhole-tests
